apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-provier
  labels:
    app: results-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-provider
  template:
    metadata:
      labels:
        app: results-provider
    spec:
      containers:
      - name: results-provider-container
        image: awesomecosmonaut/results-provider-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "250m"