apiVersion: v1
kind: Service
metadata:
  name: results-provider
  namespace: hse-coursework-health
spec:
  selector:
    app: results-provider
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP